
// Note: this file is automatically generated by MDX processing script

import { ComponentType } from 'react';


export type AppBlogPost = {
  default: ComponentType<any>,
  frontmatter: {
    title: string,
    author: string,
    date: string,
    hero: {uri: string},
    excerpt: string,
  }
}

export default [
  require('./content/posts/2019-08-20-my-first-post-using-novela-by-narative/index.mdx.jsx'),
  require('./content/posts/2019-08-30-handling-race-conditions-in-react/index.mdx.jsx'),
  require('./content/posts/2020-04-21-TODO/index.mdx.jsx'),
  require('./content/posts/2020-04-27-atomic-css-in-js/index.mdx.jsx')
] as AppBlogPost[]
