
// Note: this file is automatically generated by MDX processing script

type AppBlogPost = {
  default: any,
  _frontmatter: {
    title: string,
    author: string,
    date: string,
    hero: {uri: string},
    excerpt: string,
  }
}

export default [
  require('./content/posts/2019-08-20-my-first-post-using-novela-by-narative/index.mdx.jsx'),
  require('./content/posts/2019-08-30-handling-race-conditions-in-react/index.mdx.jsx'),
  require('./content/posts/2020-01-27-running-expo-inside-a-gatsby-blog-post/index.mdx.jsx')
] as AppBlogPost[]
